name: MyGithubActions-basics
env:
  EB_PACKAGE_S3_BUCKET_NAME: "github-packages11"
  EB_APPLICATION_NAME: Flasky
  EB_ENVIROMENT_NAME: FLASKY-env
  DEPLOY_PACKAGE_NAME: "flask_app_${{github.sha}}.zip"
  AWS_REGION_NAME: "us-east-1"

on:
  push:
    branches:
      - master

jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone repo
      uses: actions/checkout@v1
      
    - name: Create ZIp file for deploy
      run: zip -r ${{env.DEPLOY_PACKAGE_NAME}} ./ -x *.git*
      
  

